<script lang="ts">
	import { route } from '$lib/ROUTES';
</script>

<h1>Dashboard</h1>

<p>
	For save links use the <code>route()</code> function from
	<code>import &lbrace;route&rbrace; from '$lib/ROUTES';</code>. This file is generated by the build
	process and contains all the routes in your app. It will be updated automatically when you add or
	remove pages.
</p>

<a href={route('/dashboard/examples')}>Example Page</a>
